export interface Database {
  public: {
    Tables: {
      products: {
        Row: {
          id: string;
          name: string;
          description: string;
          category: string;
          type: 'material_bruto' | 'parte_produto' | 'produto_pronto';
          unit: string;
          cost_price: number;
          sale_price: number | null;
          current_stock: number;
          min_stock: number;
          supplier: string | null;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string;
          category: string;
          type: 'material_bruto' | 'parte_produto' | 'produto_pronto';
          unit: string;
          cost_price?: number;
          sale_price?: number | null;
          current_stock?: number;
          min_stock?: number;
          supplier?: string | null;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          category?: string;
          type?: 'material_bruto' | 'parte_produto' | 'produto_pronto';
          unit?: string;
          cost_price?: number;
          sale_price?: number | null;
          current_stock?: number;
          min_stock?: number;
          supplier?: string | null;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      product_components: {
        Row: {
          id: string;
          product_id: string;
          component_id: string;
          quantity: number;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          component_id: string;
          quantity: number;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          component_id?: string;
          quantity?: number;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      stock_movements: {
        Row: {
          id: string;
          product_id: string;
          movement_type: 'entrada' | 'saida';
          quantity: number;
          unit_price: number;
          total_value: number;
          project_id: string | null;
          reference_type: 'manual' | 'project' | 'adjustment';
          user_id: string;
          date: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          movement_type: 'entrada' | 'saida';
          quantity: number;
          unit_price?: number;
          total_value?: number;
          project_id?: string | null;
          reference_type?: 'manual' | 'project' | 'adjustment';
          user_id: string;
          date?: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          movement_type?: 'entrada' | 'saida';
          quantity?: number;
          unit_price?: number;
          total_value?: number;
          project_id?: string | null;
          reference_type?: 'manual' | 'project' | 'adjustment';
          user_id?: string;
          date?: string;
          notes?: string | null;
          created_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          name: string;
          type: 'pf' | 'pj';
          cpf: string | null;
          cnpj: string | null;
          email: string;
          phone: string;
          mobile: string;
          razao_social: string | null;
          inscricao_estadual: string | null;
          isento_icms: boolean;
          numero: string | null;
          complemento: string | null;
          id_empresa: string | null;
          fl_ativo: boolean;
          country: string;
          state: string;
          city: string;
          zip_code: string;
          neighborhood: string;
          street_type: string;
          street: string;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: 'pf' | 'pj';
          cpf?: string | null;
          cnpj?: string | null;
          email: string;
          phone: string;
          mobile: string;
          razao_social?: string | null;
          inscricao_estadual?: string | null;
          isento_icms?: boolean;
          numero?: string | null;
          complemento?: string | null;
          id_empresa?: string | null;
          fl_ativo?: boolean;
          country?: string;
          state: string;
          city: string;
          zip_code: string;
          neighborhood: string;
          street_type: string;
          street: string;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: 'pf' | 'pj';
          cpf?: string | null;
          cnpj?: string | null;
          email?: string;
          phone?: string;
          mobile?: string;
          razao_social?: string | null;
          inscricao_estadual?: string | null;
          isento_icms?: boolean;
          numero?: string | null;
          complemento?: string | null;
          id_empresa?: string | null;
          fl_ativo?: boolean;
          country?: string;
          state?: string;
          city?: string;
          zip_code?: string;
          neighborhood?: string;
          street_type?: string;
          street?: string;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          number: number;
          client_id: string;
          title: string;
          description: string;
          status: 'orcamento' | 'aprovado' | 'em_producao' | 'concluido' | 'entregue';
          type: 'orcamento' | 'venda';
          budget: number;
          start_date: string;
          end_date: string;
          materials_cost: number;
          labor_cost: number;
          profit_margin: number;
          payment_installments: number;
          payment_method: string | null;
          discount_percentage: number;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          number: number;
          client_id: string;
          title: string;
          description?: string;
          status: 'orcamento' | 'aprovado' | 'em_producao' | 'concluido' | 'entregue';
          type: 'orcamento' | 'venda';
          budget?: number;
          start_date: string;
          end_date: string;
          materials_cost?: number;
          labor_cost?: number;
          profit_margin?: number;
          payment_installments?: number;
          payment_method?: string | null;
          discount_percentage?: number;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          number?: number;
          client_id?: string;
          title?: string;
          description?: string;
          status?: 'orcamento' | 'aprovado' | 'em_producao' | 'concluido' | 'entregue';
          type?: 'orcamento' | 'venda';
          budget?: number;
          start_date?: string;
          end_date?: string;
          materials_cost?: number;
          labor_cost?: number;
          profit_margin?: number;
          payment_installments?: number;
          payment_method?: string | null;
          discount_percentage?: number;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      project_products: {
        Row: {
          id: string;
          project_id: string;
          product_id: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          product_id: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          user_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          product_id?: string;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          user_id?: string;
          created_at?: string;
        };
      };
      transactions: {
        Row: {
          id: string;
          project_id: string | null;
          type: 'entrada' | 'saida';
          category: string;
          description: string;
          amount: number;
          date: string;
          user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id?: string | null;
          type: 'entrada' | 'saida';
          category: string;
          description: string;
          amount: number;
          date: string;
          user_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string | null;
          type?: 'entrada' | 'saida';
          category?: string;
          description?: string;
          amount?: number;
          date?: string;
          user_id?: string;
          created_at?: string;
        };
      };
    };
  };
}
